site_name: PyPokéClient
repo_name: pokeapi-python-wrapper
repo_url: https://github.com/RistoAle97/pokeapi-python-wrapper
theme:
  name: material
  features:
    - content.code.copy
    - content.footnote.tooltips
    - content.tabs.link
    - navigation.indexes
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  font:
    text: Roboto
    code: Roboto Mono
  favicon: logo.png
  logo: logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: deep-purple
      accent: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-purple
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to system preference

extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pypokeclient/
      name: PyPI page
    - icon: fontawesome/brands/github
      link: https://github.com/RistoAle97
      name: Author's GitHub profile
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/ristoale97
      name: Author's LinkedIn profile

plugins:
  search: null
  mkdocstrings:
    handlers:
      python:
        options:
          extensions:
          - griffe_typingdoc
          - griffe_inherited_docstrings
          annotations_path: brief
          docstring_options:
            ignore_init_summary: true
          docstring_style: google
          filters: []
          members_order: source
          merge_init_into_class: true
          show_root_heading: true
          show_root_full_path: false
          separate_signature: true
          show_if_no_docstring: true
          show_labels: false
          show_signature_annotations: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - PyPokéClient:
    - Home: index.md
  - Usage:
    - Usage: usage/index.md
    - Synchronous: usage/usage_sync.md
    - Asynchronous: usage/usage_async.md
  - Reference:
    - Reference: reference/index.md
    - BaseClient: reference/base_client.md
    - Client: reference/sync_client.md
    - AsyncClient: reference/async_client.md
    - API:
      - Resource Lists/Pagination: reference/api/resource_lists.md
      - Berries:
        - Berries: reference/api/berries/berries.md
        - Berry Firmnesses: reference/api/berries/berry_firmnesses.md
        - Berry Flavors: reference/api/berries/berry_flavors.md
      - Contests:
        - Contest Types: reference/api/contests/contest_types.md
        - Contest Effects: reference/api/contests/contest_effects.md
        - Super Contest Effects: reference/api/contests/super_contest_effects.md
      - Encounters:
        - Encounter Methods: reference/api/encounters/encounter_methods.md
        - Encounter Condition: reference/api/encounters/encounter_conditions.md
        - Encounter Condition Values: reference/api/encounters/encounter_condition_values.md
      - Evolution:
        - Evolution Chains: reference/api/evolution/evolution_chains.md
        - Evolution Triggers: reference/api/evolution/evolution_triggers.md
      - Games:
        - Generations: reference/api/games/generations.md
        - Pokedexes: reference/api/games/pokedexes.md
        - Version: reference/api/games/version.md
        - Version Groups: reference/api/games/version_groups.md
      - Items:
        - Items: reference/api/items/items.md
        - Item Attributes: reference/api/items/item_attributes.md
        - Item Categories: reference/api/items/item_categories.md
        - Item Fling Effects: reference/api/items/item_fling_effects.md
        - Item Pockets: reference/api/items/item_pockets.md
      - Locations:
        - Locations: reference/api/locations/locations.md
        - Location Areas: reference/api/locations/location_areas.md
        - Pal Park Areas: reference/api/locations/pal_park_areas.md
        - Regions: reference/api/locations/regions.md
      - Machines:
        - Machines: reference/api/machines/machines.md
      - Moves:
        - Moves: reference/api/moves/moves.md
        - Move Ailments: reference/api/moves/move_ailments.md
        - Move Battle Styles: reference/api/moves/move_battle_styles.md
        - Move Categories: reference/api/moves/move_categories.md
        - Move Damage Classes: reference/api/moves/move_damage_classes.md
        - Move Learn Methods: reference/api/moves/move_learn_methods.md
        - Move Targets: reference/api/moves/move_targets.md
      - Pokémon:
        - Abilities: reference/api/pokemon/abilities.md
        - Characteristics: reference/api/pokemon/characteristics.md
        - Egg Groups: reference/api/pokemon/egg_groups.md
        - Genders: reference/api/pokemon/genders.md
        - Growth Rates: reference/api/pokemon/growth_rates.md
        - Natures: reference/api/pokemon/natures.md
        - Pokeathlon Stats: reference/api/pokemon/pokeathlon_stats.md
        - Pokemon: reference/api/pokemon/pokemon.md
        - Pokemon Location Areas: reference/api/pokemon/pokemon_location_areas.md
        - Pokemon Colors: reference/api/pokemon/pokemon_colors.md
        - Pokemon Forms: reference/api/pokemon/pokemon_forms.md
        - Pokemon Habitats: reference/api/pokemon/pokemon_habitats.md
        - Pokemon Shapes: reference/api/pokemon/pokemon_shapes.md
        - Pokemon Species: reference/api/pokemon/pokemon_species.md
        - Stats: reference/api/pokemon/stats.md
        - Types: reference/api/pokemon/types.md
      - Utility:
        - Languages: reference/api/languages.md
        - Common Models: reference/api/common_models.md
  - Contributing: contributing.md
