[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "math2remember"
version = "0.1.8"
authors = [
    {name = "ChDxterWard"},
]
description = ""
readme = "README.md"
license = {text = "MIT"}
keywords = ["math"]
classifiers = [
    "Programming Language :: Python :: 3",
]

[project.urls]
Homepage = "https://github.com/ChDxterWard/math2remember"
Repository = "https://github.com/ChDxterWard/math2remember"
"Bug Reports" = "https://github.com/ChDxterWard/math2remember/issues"