[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "prism-ssl"
version = "0.1.0"
description = "A Self-Supervised Learning Library"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
  { name = "Kianoosh Vadaei", email = "kia.vadaei@gmail.com" },
  { name = "Melika Shirian" }
]
requires-python = ">=3.10"
dependencies = [
  "axial_positional_embedding",
  "colorlog",
  "editdistance",
  "einops",
  "huggingface_hub",
  "jiwer",
  "joblib",
  "numpy",
  "opencv_python",
  "optuna",
  "pandas",
  "peft",
  "Pillow",
  "plotly",
  "scikit_learn",
  "setuptools",
  "torch",
  "torch_geometric",
  "torchaudio",
  "torcheval",
  "torchmetrics",
  "torchvision",
  "tqdm",
  "transformers",
  "wandb"
]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "Intended Audience :: Education",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]
Homepage = "https://github.com/PrismaticLab/PrismSSL"

