[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "qugradlab"
version = "0.1.2"
authors = [
  { name="Christopher K. Long", email="ckl45@cam.ac.uk" },
  { name="Crispin H. W. Barnes" },
  { name="David R. M. Arvidsson-Shukur" },
  { name="Normann Mertig" }
]
maintainers = [
  { name="Christopher K. Long", email="ckl45@cam.ac.uk" },
]
description = "An extension to the Python package QuGrad that implements common Hilbert space structures, Hamiltonians, and pulse shapes for quantum control."
keywords = ["Hamiltonian", "pulse", "control"]
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Quantum Computing"
]
license = "Apache-2.0"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "scipy == 1.*", # Major version change may be backwards incompatible. See https://docs.scipy.org/doc/scipy/dev/core-dev/index.html#version-numbering
    "numpy >= 1.21, < 3", # Major version change will likely indicate an ABI break. See https://numpy.org/doc/stable/dev/depending_on_numpy.html
    "qugrad == 1.*", # Follows semantic versioning. See https://qugrad.readthedocs.io
    "py-ste == 1.*", # Follows semantic versioning. See https://PySTE.readthedocs.io
    "tensorflow == 2.*" # Follows semantic versioning. See https://www.tensorflow.org/guide/versions
]

[project.urls]
Homepage = "https://github.com/Christopher-K-Long/QuGrad"
Documentation = "https://QuGrad.readthedocs.io/"
Issues = "https://github.com/Christopher-K-Long/QuGrad/issues"
Changelog = "https://github.com/Christopher-K-Long/QuGrad/blob/main/ChangeLog.md"