[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "copul"
version = "0.3.8"
description = "A Python package for copula analysis and computation."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "Marcus Rockel", email = "marcus.rockel@finance.uni-freiburg.de"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "pandas>=2.3",
    "sympy>=1.14",
    "numpy>=2.0",
    "scipy>=1.14",
    "matplotlib>=3.9",
    "sympy-plot-backends>=3.1",
    "statsmodels>=0.14",
    "typing-extensions>=4.15.0",
]

[project.urls]
"Repository" = "https://github.com/Corrram/copul"
"Documentation" = "https://copul.readthedocs.io"
"Issue Tracker" = "https://github.com/Corrram/copul/issues"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
addopts = "-ra -q"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "instable: marks tests as instable (deselect with '-m \"not instable\"')",
]

[project.optional-dependencies]
dev = [
    "black>=24.8",
    "build>=0.10.0",
    "cvxpy>=1.7.1",
    "jupyter>=1.0.0",
    "mypy>=1.0.0",
    "pylint>=2.17.0",
    "pytest-cov>=5.0.0",
    "pytest-xdist>=3.6.1",
    "sphinx-rtd-theme>=2.0",
    "sphinx>=7.4",
    "pytest>=8.3.5",
    "ruff>=0.9.9",
    "twine>=6.1.0",
    "hatchling>=1.27.0",
    "seaborn>=0.13.2",
]
