name: Release to PyPI

on:
  push:
    tags:
      - 'v*.*.*'   # Only trigger on version tags

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install build dependencies
      run: |
          python -m pip install --upgrade pip
          pip install numpy pandas onnx jinja2 loguru typer fmpy cmake
          pip install flit
          pip install -e .

    - name: Check version matches tag
      run: |
        PYPROJECT_VERSION=$(grep -Po '(?<=^version = ")[^"]*' pyproject.toml)
        GIT_TAG=${GITHUB_REF#refs/tags/v}
        echo "pyproject.toml version: $PYPROJECT_VERSION"
        echo "Git tag: $GIT_TAG"
        if [ "$PYPROJECT_VERSION" != "$GIT_TAG" ]; then
          echo "âŒ Version mismatch between pyproject.toml ($PYPROJECT_VERSION) and Git tag ($GIT_TAG)"
          exit 1
        fi

    - name: Publish to PyPI using flit
      env:
        FLIT_INDEX_URL: https://upload.pypi.org/legacy/
        FLIT_USERNAME: __token__
        FLIT_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        flit publish