[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyawsmock"
version = "0.1.2"
description = "Local AWS Mock for Python â€“ Mock SSM Parameter Store, S3, CodeArtifact, and extendable AWS services"
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "coldsofttech" }]
requires-python = ">=3.10"
dependencies = [
    "boto3~=1.40.55",
    "filelock~=3.20.0",
    "crcmod~=1.7"
]