[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mixedassembly"
version = "0.2.1"
description = "Tools for consensus sequences mixing and frameshift correction (mixedAssembly)"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
  { name = "GermÃ¡n Vallejo Palma", email = "german.vallejo@isciii.es" }
]
requires-python = ">=3.8"
dependencies = [
  "biopython>=1.79",
  "numpy>=1.21",
  "pandas>=1.3",
  "pyarrow>=12.0"  
]

[project.scripts]
mixedassembly = "mixedassembly.cli:main"

[project.urls]
Homepage = "https://github.com/GERMAN00VP/mixedAssembly/tree/viralrecon_version"
