[project]
name = "sdml-kafka-client"
version = "0.1.1"
description = "Kafka client for SDML"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["aiokafka>=0.12.0", "beartype>=0.22.2", "loguru>=0.7.3"]
