[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "python-project-template-AS"
description = "A minimal Python project demonstrating best practices for testing, documentation, and CI/CD. It implements a mini calculator as a minimal example."
version = "0.1.1"
readme = "README.md"
requires-python = ">=3.8"
authors = [{ name = "Andrea Scaglioni", email = "andrea.c.scaglioni@gmail.com" }]
keywords = ["example", "template", "project-template", "pytest", "sphinx", "CI/CD"]
license = { text = "MIT" }
dependencies = []
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/andreascaglioni/python-project-template"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = ["-q","--strict-markers", "--disable-warnings", "--cov=src", "--cov-report=term-missing", "--cov-fail-under=85"]
markers = [
  "integration: marks integration tests (deselect with '-m \"not integration\"')",
  "slow: marks slow tests",
]

# --- Optional dependencies for development. Run pip install -e ".[dev]"
[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-cov",
  "pre-commit",
  "black",
  "ruff",
  "mypy",
]

# --- Optional dependencies for compiling the documentation. Run: pip install -e ".[docs]"
docs = [
  "sphinx>=7.0",                 # provides sphinx.ext.* (autodoc, napoleon, autosummary, viewcode, ...)
  "pydata-sphinx-theme",         # theme used in docs/conf.py (pydata_sphinx_theme)
  "sphinx-autodoc-typehints",    # provides extension `sphinx_autodoc_typehints`
  "sphinx-mdinclude",            # provides extension (sphinx_mdinclude)
  "sphinx-copybutton",           # provides extension `sphinx_copybutton`
  "sphinxcontrib-spelling",      # spell-checking documentation
]
