gemini-2.5-pro:
  name: gemini-2.5-pro
  api: gemini
  call_delay: 5.0
  retry_delay: 30.0

gemini-2.5-flash:
  name: gemini-2.5-flash
  api: gemini
  call_delay: 10.0
  retry_delay: 15.0

mistral-large-latest:
  name: mistral-large-latest
  api: mistral
  call_delay: 2.0
  retry_delay: 20.0

mistral-medium-latest:
  name: mistral-medium-latest
  api: mistral
  call_delay: 2.0
  retry_delay: 20.0

mistral-small-latest:
  name: mistral-small-latest
  api: mistral
  call_delay: 2.0
  retry_delay: 20.0

magistral-medium-latest:
  name: magistral-medium-latest
  api: mistral
  call_delay: 2.0
  retry_delay: 20.0