[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "github-release-counter"
version = "1.1.0"
authors = [
  { name="Marco ML", email="marcoleija@marco-ml.com" },
]
description = "A Python tool to count GitHub release downloads."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests",
]

[project.urls]
Homepage = "https://github.com/marcomolinaleija/github-release-counter"

[project.scripts]
github-release-counter = "github_release_counter.cli:main"
grc = "github_release_counter.cli:main"