[project]
name = "qltool"
version = "0.2.4"
description = "PRINT simple labels on ql700"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.2.1",
    "console>=0.9911",
    "importlib-resources>=6.5.2",
    "opencv-python>=4.12.0.88",
    "paho-mqtt>=2.1.0",
    "pillow>=11.3.0",
    "qrcode>=8.2",
]

[project.scripts]
qltool = "qltool.main:cli"
qltool_client = "qltool.client:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
