[project]
authors = [{ name = "Allen Chou", email = "f1470891079@gmail.com" }]
dependencies = [
  "bs4",
  "cachetic",
  "dictpress",
  "fastapi",
  "httpx",
  "huey",
  "logfire",
  "logging_bullet_train",
  "openai (>=1,<2)",
  "openai-agents (>=0.1.0,<1.0.0)",
  "playwright",
  "pydantic (>=2)",
  "pydantic-settings",
  "str-or-none",
  "tiktoken",
  "yarl",
]
description = "Get web content from queue."
license = { text = "MIT" }
name = "web-queue2"
readme = "README.md"
requires-python = ">=3.11,<4"
version = "0.1.0"

[project.urls]
Homepage = "https://github.com/allen2c/web-queue"
"PyPI" = "https://pypi.org/project/web-queue/"
Repository = "https://github.com/allen2c/web-queue"

[tool.poetry]
packages = [{ include = "web_queue" }]

[tool.poetry.extras]
all = []

[tool.poetry.group.dev.dependencies]
black = { extras = ["jupyter"], version = "*" }
isort = "*"
poetry-plugin-export = "*"
pytest = "*"
pytest-asyncio = "*"
pytest-cov = "*"
pytest-env = "*"
pytest-xdist = "*"
rich = "*"
rich-color-support = "*"
setuptools = "*"
twine = "*"

[tool.isort]
profile = "black"

[tool.flake8]
ignore = ["E203", "E704", "W503"]
max-line-length = 88

[tool.pytest.ini_options]
env = ["ENVIRONMENT=test", "PYTEST_IS_RUNNING=true"]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=2.0.0,<3.0.0"]
