[build-system]
requires = ["setuptools>=67.0"]
build-backend = "setuptools.build_meta"
[project]
name = "comed-prices"
version = "0.0.1"
authors = [
    {name="Alexander Fedotov", email="alex.fedotov@aol.com"},
]
description = "ComEd hourly and 5 minute prices"
readme = "README.md"
requires-python = ">=3.10"
classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
]
keywords = ["ComEd", "prices", "hourly"]
dependencies = [
    "requests >= 2.31.0"
]
[project.urls]
"Homepage" = "https://github.com/alxfed/comed-prices"
"Bug Tracker" = "https://github.com/alxfed/comed-prices/issues"
