[build-system]
requires = [
  "maturin>=1.8,<2.0"
]
build-backend = "maturin"

[project]
name = "czkawka"
description = "Python bindings for the Czkawka Rust library, a fast image similarity engine"
classifiers = [
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Rust",
  "Programming Language :: Python :: Implementation :: CPython",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9"
]
authors = [
  {email = "louismmx@gmail.com", name = "Louis Maddox"}
]
keywords = [
  "image",
  "similarity",
  "rust",
  "deduplication",
  "perceptual-hash"
]
readme = "README.md"
requires-python = ">=3.8"
version = "0.1.2"

[project.license]
file = "LICENSE"

[dependency-groups]
build = ["maturin>=1.9.3", "patchelf>=0.17.2.4"]
dev = [
  "pdbpp>=0.11.7",
  # PDM stopped supporting Python 3.8+ in 2.21
  "pdm>=2.20,<2.21",
  # Cannot use pdm-bump with 3.8
  # "pdm-bump>=0.9.10",
  # "pre-commit>=4.1.0"
]
# doc = [
#   "livereload>=2.7.1",
#   "mdx-truly-sane-lists>=1.3",
#   "mkdocs-extra-sass-mathshim>=0.1.1",
#   "mkdocs-material[imaging,recommended]>=9.6.18",
#   "mkdocs-section-index>=0.3.10",
#   "mkdocs>=1.6.1",
#   "mkdocstrings[python]>=0.30.0",
#   "ruff>=0.12.10",
#   "urllib3<2",
# ]
test = [
    "pillow<=11.0.0",
    "pytest-benchmark<=5.0.0",
    "pytest<=8.4.0",
]

[tool.ruff.lint]
# default: select = ["E4", "E7", "E9", "F"]
select = ["E4", "E7", "E9", "F", "D", "UP"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[project.urls]
Homepage = "https://github.com/lmmx/czkawka"
Repository = "https://github.com/lmmx/czkawka.git"

[tool.maturin]
features = [
  "pyo3/extension-module"
]
module-name = "czkawka._czkawka"
python-source = "python"

[tool.uv]
# Build Rust code in development mode (faster builds)
# config-settings = { build-args = "--profile=dev" }
default-groups = ["build", "dev", "test"]
