[tool.poetry]
name = "bella-companion"
version = "0.0.29"
description = ""
authors = ["gabriele-marino <gabmarino.8601@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

arviz = "^0.22.0"
bella-lumiere = "^0.0.14"
dotenv = "^0.9.9"
phylogenie = "^3.1.2"
seaborn = "^0.13.2"

[tool.poetry.scripts]
bella = "bella_companion.cli:main"

[tool.poetry.group.dev.dependencies]
joblib-stubs = "^1.5.2.0.20250831"
pyright = "^1.1.406"

[tool.pyright]
typeCheckingMode = "strict"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
