[project]
name = "exoanchor"
version = "0.1.0"
description = "A CLI tool to test if your Python project will break before you upgrade dependencies."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [
  { name = "Jonathan R Belanger", email = "jonathan.r.belanger@gmail.com" },
]

dependencies = [
    "click",
    "requests",
    "packaging",
]

[project.scripts]
exoanchor = "exoanchor.cli:run"
