[project]
name = "ifunctions"
version = "0.2.4"
description = "100% Python native â€” tanpa ketergantungan pada library pihak ketiga."
readme = "README.md"
authors = [
    { name = "arbadzukhron", email = "dzukhronufiaarba@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
i = "ifunctions:main"
