[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyDWS"
version = "1.1.1"
description = "A Python package for the analysis of Diffusing Wave Spectroscopy and tracer bead microrheology data."
authors = [
    { name="M. Helfer, C. Zhang, and F. Scheffold", email="frank.scheffold@unifr.ch" }
]
readme = { file = "README.md", content-type = "text/markdown" }
license = {text = "MIT"}
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.21.0",
    "matplotlib>=3.4.3",
    "pandas>=1.3.0",
	"scikit_learn>=1.0.0",
	"scipy>=1.7.0",
	"statsmodels>=0.14.5"
]

[project.optional-dependencies]
dev = ["jupyter"]

[tool.setuptools]
packages = ["pyDWS"]

[tool.setuptools.package-data]
pyDWS = ["*.mplstyle"]


[project.urls]
"Homepage" = "https://github.com/ManuelH26/pyDWS"
"Bug Tracker" = "https://github.com/ManuelH26/pyDWS/issues"
"Source Code" = "https://github.com/ManuelH26/pyDWS"