[tool.poetry]
name = "glycogym"
version = "1.0.1"
repository = "https://github.com/BojarLab/GlycoGym"
readme = "README.md"
description = "A benchmark collection for glycan property prediction with tasks from variuos, glycobiologically relevant tasks."
authors = ["Roman Joeres <roman.joeres@helmholtz-hips.de>"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]

[tool.poetry.dependencies]
python = ">=3.10"
datasail = ">=1.2.3"
glycowork = "*"
nxontology = "*"
numpy-indexed = "*"
glyles = ">=1.2.3a0"
platformdirs = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"
sphinx-rtd-theme = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
