[tool.poetry]
name = "spaceblocks-permissions-server"
version = "4.0.0"
description = "Server SDK for Space Blocks Permissions, a permissions-as-a-service platform for developers"
authors = ["Space Blocks Team <hello@spaceblocks.cloud>"]
license = "MIT"
readme = "README.md"
homepage = "https://spaceblocks.cloud"
documentation = "https://docs.spaceblocks.cloud/permissions"
keywords = ["space blocks", "permissions", "rbac"]
include = ["spaceblocks_permissions_server/py.typed"]

[tool.poetry.dependencies]
python = "^3.8"
urllib3 = ">= 1.25.3"
python-dateutil = ">=2.8.2"
pydantic = ">=2"
typing-extensions = ">=4.7.1"
pyjwt = "^2.9.0"

[tool.poetry.group.dev.dependencies]
pytest = ">=7.2.1"
pylint = "^3.1.0"
flake8 = ">=4.0.0"
flake8-pyproject = "^1.2.3"
mypy = "1.4.1"
types-python-dateutil = ">=2.8.19.14"

[tool.pylint.format]
max-line-length = 120

[tool.pylint.message-control]
extension-pkg-whitelist = "pydantic"
disable = ["too-many-return-statements", "too-many-instance-attributes"]

[tool.flake8]
max-line-length = 120
disable-noqa = true
per-file-ignores = ["__init__.py:F401", "test_*.py:F401,F811"]

[tool.mypy]
mypy_path = ".mypy_stubs"
strict = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
