[build-system]
requires = [
    "setuptools >= 65",
    "wheel >= 0.38",
    "setuptools_scm", # for automatic versioning
]
build-backend = "setuptools.build_meta"

[project]
# name: String, REQUIRED
name = "MoleCool"

# version: String, REQUIRED
# Should follow PEP 440 rules
# Can be provided dynamically, see the lesson on publishing
# version = "3.4.2"
dynamic = ["version"]

# description: String
# A simple summary of the project
description = "Molecular Laser-Cooling and Spectra Simulation"

keywords = [
    "cold molecules",
    "laser cooling",
    "optical Bloch equations",
    "rate equations",
    "diatomic molecules",
    "multi-level systems",
    "Rabi-oscillations",
    "coherent laser forces"
    ]

# readme: String
# Full description of the project.
# Should be the path to your README file, relative to pyproject.toml
readme = "README.md"

# requires-python: String
# The Python version required by the project
requires-python = ">=3.8"

# license:
license = "MIT" # SPDX-style string
license-files = ["LICENSE.md"] # include actual license file

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Topic :: Scientific/Engineering :: Physics",
]

# authors: Array of Tables
# Can also be called 'maintainers'.
# Each entry can have a name and/or an email
authors = [
    {name = "Felix Kogel", email = "felix.kogel@t-online.de"},
]

# dependencies: Array of Strings
# A list of requirements for our package
dependencies = [
    "numpy < 2.0",
    "numba >= 0.53.1",
    "pandas < 1.4",
    "scipy >= 1.5.4",
    "sympy < 1.13",
    "tqdm",
    "matplotlib",
    "h5py",
]

[project.optional-dependencies]
doc = [
    "sphinx", # Core requirement
    "sphinx-book-theme", # Theme
    "sphinx-gallery", # auto-generated examples in a gallery
    "sphinx-copybutton",
    "sphinx-design", # design elements
    "sphinx-exec-code", # execute individual code blocks
    # "myst-nb",
]
dev = [
    "setuptools>=42",
    "wheel",
    "setuptools-scm",
    "build", # standard tool to create a wheel file for uploading included in ./dist
    "twine", # tool for uploading our package to PyPI
    #"scikit-optimize==0.9.0", # for bayesian optimization
]

[project.urls]
# urls: Table
# Should describe where to find useful info for your project
# source = "github.com/MyProfile/my_project"
Homepage = "https://www.coldmolecules.eu/Home/"
Documentation = "https://molecool.readthedocs.io/en/stable"
Repository = "https://github.com/LangenGroup/MoleCool"
Issues = "https://github.com/LangenGroup/MoleCool/issues"

[tool.setuptools.package-data]
"MoleCool" = ["constants/*.json"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["MoleCool*"]

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "no-local-version" # "node-and-date"
write_to = "MoleCool/_version.py"