---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: \.json$|\.ipynb$
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer
        exclude: \.ipynb$
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-toml
      - id: check-yaml
      - id: name-tests-test
        args: [--pytest-test-first]
        exclude: ^tests/test_data/|^tests/helpers\.py$
      - id: check-merge-conflict
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/jsh9/muff-pre-commit
    rev: 0.13.2
    hooks:
      - id: muff-format
        args: [--config, muff.toml]
  - repo: https://github.com/jsh9/blank-line-after-blocks
    rev: 0.1.4
    hooks:
      - id: blank-line-after-blocks
      - id: blank-line-after-blocks-jupyter
  - repo: https://github.com/lyz-code/yamlfix
    rev: 1.18.0
    hooks:
      - id: yamlfix
  - repo: https://github.com/hukkin/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        args: [--wrap, '79', --number]
        additional_dependencies: [mdformat-gfm]
  - repo: https://github.com/jsh9/format-json
    rev: 0.1.2
    hooks:
      - id: format-json
        args:
          - --autofix
          - --no-ensure-ascii
          - --indent=4
          - --no-sort-keys
          - --no-eof-newline
  - repo: https://github.com/jsh9/markdown-toc-creator
    rev: 0.0.11
    hooks:
      - id: markdown-toc-creator
  - repo: https://github.com/jsh9/markdown-heading-numbering
    rev: 0.1.0
    hooks:
      - id: markdown-heading-numbering
        exclude: ^CHANGELOG\.md$
  - repo: local
    hooks:
      - id: format-docstring
        name: Format self (python docstrings)
        entry: python
        args: [-m, format_docstring.main_py, --verbose, diff]
        language: python
        types: [python]
        exclude: ^tests/test_data/
        additional_dependencies:
          - click>=8.0
          - jupyter-notebook-parser>=0.1.4
          - tomli>=1.1.0
      - id: format-docstring-jupyter
        name: Format self (docstrings in Jupyter notebooks)
        entry: python
        args: [-m, format_docstring.main_jupyter, --verbose, diff]
        language: python
        files: ^.*\.ipynb$
        exclude: ^tests/test_data/
        additional_dependencies:
          - click>=8.0
          - jupyter-notebook-parser>=0.1.4
          - tomli>=1.1.0
