[project]
name = "physics-plot"
version = "0.2.1"
description = "matplotlib styles and utils"
readme = "README.md"
authors = [
    { name = "Cory Chu", email = "cory@gwlab.page" }
]
requires-python = ">=3.9"
dependencies = []

[project.urls]
Homepage = "https://github.com/c0rychu/physics-plot"
Documentation = "https://c0rychu.github.io/physics-plot/"
Repository = "https://github.com/c0rychu/physics-plot.git"
Issues = "https://github.com/c0rychu/physics-plot/issues"

[build-system]
requires = ["uv_build>=0.9.0,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "black>=24.8.0",
    "ipykernel>=6.29.5",
    "matplotlib>=3.7.5",
    "mkdocs-material>=9.6.22",
    "mkdocstrings[python]>=0.26.2",
    "numpy>=1.24.4",
    "pip>=25.0.1",
    "pre-commit>=3.5.0",
    "pytest>=8.3.5",
    "ruff>=0.14.0",
]

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
target-version = "py311"
line-length = 88

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
