[tool.poetry]
name = "shop_system_models"
version = "v1.4.0"
description = "Shared model definitions for shop system services"
authors = ["Pavel Mulin <pavel@tg-shops.com>"]
readme = "README.md"
packages = [{ include = "shop_system_models" }]
include = ["shop_system_models/py.typed"]  # ðŸ‘ˆ Ð’Ð¾Ñ‚ ÑÑŽÐ´Ð°!

[tool.poetry.dependencies]
python = ">=3.9"
pydantic = ">=2.10.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
